version: "3.9"

services:
  hdm-db:
    image: postgres:16-alpine
    container_name: hdm-database
    restart: unless-stopped
    environment:
      POSTGRES_DB:       hdm_db
      POSTGRES_USER:     hdm_user
      POSTGRES_PASSWORD: hdm_pass_2024   # Cambiar en producción
      PGDATA:            /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - hdm_pgdata:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d   # Init automático al primer arranque
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hdm_user -d hdm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hdm-net

volumes:
  hdm_pgdata:

networks:
  hdm-net:
    driver: bridge
